[package]
name = "bizwiz3/loader"
description = "A simple way to create a single-script structure."
version = "0.1.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/BizWiz3/Loader"

[dependencies]
